name: muslim_id
description: Aplikasi Islam

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.2.11
  intl: ^0.15.8
  fluttery: ^0.0.8
  http: ^0.12.0+2
  flutter_compass: ^0.3.2
  permission_handler: ^3.1.0
  flutter_spinkit: ^3.1.0
  location: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
